M48
; DRILL file {KiCad 9.0.6} date 2026-04-03T23:40:38-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-03T23:40:38-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.200
%
G90
G05
T1
X63.11Y-40.355
X67.96Y-40.355
T2
X59.835Y-37.825
X59.835Y-84.825
X71.235Y-37.825
X71.235Y-84.825
T3
X62.81Y-37.325
X68.26Y-37.325
T4
X28.2Y-28.2
X121.8Y-28.2
M30
